syms S Q R D Q_s R_s D_s beta gamma muI beta_s dt
jacobian([ ...
S - ((beta*S*Q + beta_s*S*Q_s)/Npop)*dt, ...
Q + (beta*S*Q/Npop - (gamma+muI)*Q)*dt, ...
R + gamma*Q*dt, ...
D + muI*Q*dt, ...
Q_s + (beta_s*S*Q_s/Npop - (gamma+muI)*Q_s)*dt, ...
R_s + gamma*Q_s*dt, ...
D_s + muI*Q_s*dt], [S Q R D Q_s R_s D_s])